---
title: "Density Plots"
author: "Ani Khachatryan"
date: "3/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir='E:/Columbia/Spring2020/lab/data/')
```

Load the DECIPHER genes
```{r}
decipher_genes <- read.csv('./DDD/DDG2P_28_1_2020.csv')
decipher_genes_confirmed <- subset(decipher_genes, DDD.category == 'confirmed')
decipher_genes_confirmed$gene.symbol <- tolower(decipher_genes_confirmed$gene.symbol)
decipher_genes_confirmed$organ.specificity.list <- tolower(decipher_genes_confirmed$organ.specificity.list)
print(dim(decipher_genes_confirmed)[1])
```

Plotting function
```{r}
plot_density <- function(df, organ, title, cutoff=NULL) {
  myfun <- function(mystr) {
    return(grepl(organ, mystr, fixed=TRUE))
  }
  rownames(df) <- make.unique(tolower(rownames(df)))
  
  # new step: find risk genes in that organ
  # get the risk genes in this specific organ
  decipher_genes_confirmed_organ <- decipher_genes_confirmed[unlist(lapply(decipher_genes_confirmed$organ.specificity.list, myfun)), ]
  
  df_risk <- df[rownames(df) %in% decipher_genes_confirmed_organ$gene.symbol, ]
  df_means <- data.frame(rowMeans(df))

  # get only risk and non-risk genes, remove risk non-organ and non-confirmed risk genes  
  df_means_risk <- df_means[rownames(df_means) %in% decipher_genes_confirmed_organ$gene.symbol, ]
  df_means_non_risk <- df_means[((rownames(df_means) %in% decipher_genes_confirmed_organ$gene.symbol) + (rownames(df_means) %in% decipher_genes$gene.symbol) != 1), ]
  df_means_non_risk_non_zero <- df_means_non_risk[!(df_means_non_risk==0)]
  
  # trim outliers
  # cut at 99th percentile
  if (is.null(cutoff)) {
    cutoff_risk <- quantile(df_means_risk, c(.95))
    cutoff_non_risk <- quantile(df_means_non_risk_non_zero, c(.95))
  } else if (cutoff == 'no cutoff') {
    cutoff_risk <- max(df_means_risk)
    cutoff_non_risk <- max(df_means_non_risk_non_zero)
  } else {
    cutoff_risk <- cutoff
    cutoff_non_risk <- cutoff
  }
  
  df_density <- data.frame('EL' = df_means_risk[df_means_risk <= cutoff_risk])
  l <- dim(df_density)[1]
  df_means_non_risk_non_zero <- data.frame('EL' = df_means_non_risk_non_zero[df_means_non_risk_non_zero <= cutoff_non_risk])
  
  print(paste0('number of risk genes in ', organ, ': ', length(df_means_risk)))
  print(paste(mean(df_means_risk), 'mean EL in risk genes vs', 
              mean(df_means_non_risk_non_zero$EL), 'mean non-zero EL in non-risk genes'))
  
  # randomly choose non-risk
  non_risk_EL <- sample(df_means_non_risk_non_zero$EL, size=l, 
                       replace=FALSE)
  
  # bind
  df_density <- rbind(df_density, data.frame('EL'=non_risk_EL))
  df_density <- cbind(df_density, 'label'=c(rep('risk', l), rep('non-risk', l)))
  
  # plot
  ggplot(df_density, aes(x=EL, fill=label)) +
    geom_density(alpha=0.7) +
    xlab("Expression Level") +
    ggtitle(title) +
    theme(plot.title = element_text(hjust = 0.5))
  
}
```

**1. Tabula Muris data**

**1.1 TM Brain (Myeloid) data**
```{r}
tm_brain_myeloid_data_qc_norm <- read.csv('./scRNA-seq/TabulaMuris/FACS/qc_norm/Brain_Myeloid-counts_qc_norm.csv', check.names=FALSE, row.names=1)

plot_density(df=tm_brain_myeloid_data_qc_norm, organ='brain', title='TM Brain (Myeloid)', cutoff=NULL)
```


**1.2 TM Brain (Non-Myeloid) data**
```{r}
# Load filtered and normalized data
tm_brain_non_myeloid_data_qc_norm <- read.csv('./scRNA-seq/TabulaMuris/FACS/qc_norm/Brain_Non-Myeloid-counts_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=tm_brain_non_myeloid_data_qc_norm, organ='brain', title='TM Brain (Non-Myeloid)', cutoff=NULL)
```


**1.3. Tabula Muris(FACS) Heart data.**
```{r}
tm_heart_data_qc_norm <- read.csv('./scRNA-seq/TabulaMuris/FACS/qc_norm/Heart-counts_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=tm_heart_data_qc_norm, organ='heart', title='TM Heart', cutoff=NULL)

```

**1.4. Tabula Muris(FACS) Lung data.**
```{r}
tm_lung_data_qc_norm <- read.csv('./scRNA-seq/TabulaMuris/FACS/qc_norm/Lung-counts_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=tm_lung_data_qc_norm, organ='lung', title='TM Lung', cutoff=NULL)

```

**1.5. Tabula Muris(FACS) Kidney data.**
```{r}
tm_kidney_data_norm <- read.csv('./scRNA-seq/TabulaMuris/FACS/qc_norm/Kidney-counts_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=tm_kidney_data_norm, organ='kidney', title='TM Kidney', cutoff=NULL)

```

**2. Zhong 2018 data**
```{r}
zhong2018_data_qc_norm <- read.csv('./scRNA-seq/zhong2018/qc_norm/GSE104276_all_pfc_2394_UMI_count_NOERCC_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=zhong2018_data_qc_norm, organ='brain', title='Zhong 2018', cutoff=NULL)
```

**3. La Manno 2016**
```{r}
lamanno2016_data_qc_norm <- read.csv('./scRNA-seq/lamanno2016/qc_norm/GSE76381_EmbryoMoleculeCounts.cef_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=lamanno2016_data_qc_norm, organ='brain', title='La Manno 2016', cutoff=NULL)
```

**4. Hodge 2019**
```{r}
hodge2019_data_qc_norm <- read.csv('./scRNA-seq/hodge2019/data2/qc_norm/trimmed_means_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=hodge2019_data_qc_norm, organ='brain', title='Hodge 2019', cutoff=NULL)
```

**5. Asp 2019**
```{r}
asp2019_data_qc_norm <- read.csv('./scRNA-seq/asp2019/filtered_count_matrices_and_meta_tables/share_files/qc_norm/fixed_all_cells_meta_data_filtered_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=asp2019_data_qc_norm, organ='heart', title='Asp 2019', cutoff=NULL)
```

**6. Nowakowski 2017**
```{r}
nowakowski2017_data_qc_norm <- read.csv('./scRNA-seq/nowakowski2017/qc_norm/exprMatrix_qc_norm.csv', check.names=FALSE, row.names = 1)

plot_density(df=nowakowski2017_data_qc_norm, organ='brain', title='Nowakowski 2017', cutoff=NULL)
```

